{
 "title": "CLCplus Backbone - Processing Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "select service_name from customer.services where service_name!='logger' and  service_name!='state'"
   },
   {
    "name": "task",
    "query": "select task_name from customer.tasks union select 'main' as task_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"color:Whitehite\">Not started yet (-2)</span>\n<br>\n<span style=\"color:Red\">Failed (-1)</span>\n<br>\n<span style=\"color:Yellow\">Received, Queued, Running (0)</span>\n<br>\n<span style=\"color:Green\">Success (1)</span>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processing Status",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 23, "w": 21, "x": 3, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n\tcri.cellcode as name,\n\tST_Y(ST_Transform(cri.geom, 4326)) as latitude,\n\tST_X(ST_Transform(cri.geom, 4326)) as longitude,\n\tMAX(case when '[[task]]' = 'main' and mar.order_status = 'FAILED' then -1 when '[[task]]' = 'main' and (mar.order_status = 'RUNNING' or mar.order_status = 'RECEIVED' or mar.order_status = 'QUEUED') then 0 when '[[task]]' = 'main' and mar.order_status = 'SUCCESS' then 1 when '[[task]]' != 'main' and mar.task_status = 'FAILED' then -1 when '[[task]]' != 'main' and (mar.task_status = 'RUNNING' or mar.task_status = 'RECEIVED' or mar.task_status = 'QUEUED') then 0 when '[[task]]' != 'main' and mar.task_status = 'SUCCESS' then 1 else -2 end) as value,\n\tMAX(case when '[[task]]' = 'main' and mar.order_status = 'FAILED' then -1 when '[[task]]' = 'main' and (mar.order_status = 'RUNNING' or mar.order_status = 'RECEIVED' or mar.order_status = 'QUEUED') then 0 when '[[task]]' = 'main' and mar.order_status = 'SUCCESS' then 1 when '[[task]]' != 'main' and mar.task_status = 'FAILED' then -1 when '[[task]]' != 'main' and (mar.task_status = 'RUNNING' or mar.task_status = 'RECEIVED' or mar.task_status = 'QUEUED') then 0 when '[[task]]' != 'main' and mar.task_status = 'SUCCESS' then 1 else -2 end) as metric\nfrom\n\tgrafana_monitoring.europe_10km_eea39_centroids cri left outer join\n\t(select * from customer.manual_and_automatic_requests where service_name = '[[service]]' and (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))) as mar on (cri.cellcode=mar.cellcode)\ngroup by\n\tcri.geom,\n\tname"
    }
   ]
  },
  {
   "title": "Progress (%)",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcase when '[[task]]'='main' then 100/571200. * COUNT(order_status) else 100/571200. * COUNT(task_status) end as success\nfrom\n\tcustomer.manual_and_automatic_requests\nwhere\n\tservice_name = '[[service]]'\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n\tand (('[[task]]' = 'main' and order_status = 'SUCCESS') or ('[[task]]' != 'main' and task_status ='SUCCESS'))"
    },
    {
     "rawSql": "select\n\tcase when '[[task]]'='main' then 100/571200. * COUNT(order_status) else 100/571200. * COUNT(task_status) end as failed\nfrom\n\tcustomer.manual_and_automatic_requests\nwhere\n\tservice_name = '[[service]]'\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n\tand (('[[task]]' = 'main' and order_status = 'FAILED') or ('[[task]]' != 'main' and task_status ='FAILED'))"
    },
    {
     "rawSql": "select\n\tcase when '[[task]]'='main' then 100/571200. * COUNT(order_status) else 100/571200. * COUNT(task_status) end as running\nfrom\n\tcustomer.manual_and_automatic_requests\nwhere\n\tservice_name = '[[service]]'\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n\tand (('[[task]]' = 'main' and order_status = 'RUNNING') or ('[[task]]' != 'main' and task_status ='RUNNING'))"
    },
    {
     "rawSql": "select\n\tcase when '[[task]]'='main' then 100/571200. * COUNT(order_status) else 100/571200. * COUNT(task_status) end as queued\nfrom\n\tcustomer.manual_and_automatic_requests\nwhere\n\tservice_name = '[[service]]'\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n\tand (('[[task]]' = 'main' and order_status = 'QUEUED') or ('[[task]]' != 'main' and task_status ='QUEUED'))"
    },
    {
     "rawSql": "select\n\tcase when '[[task]]'='main' then 100/571200. * COUNT(order_status) else 100/571200. * COUNT(task_status) end as received\nfrom\n\tcustomer.manual_and_automatic_requests\nwhere\n\tservice_name = '[[service]]'\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n\tand (('[[task]]' = 'main' and order_status = 'RECEIVED') or ('[[task]]' != 'main' and task_status ='RECEIVED'))"
    }
   ]
  },
  {
   "title": "Request by User",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\tcase when '[[task]]'='main' then order_username else task_username end as username,\r\n\tcount(*)\r\nfrom\r\n\tcustomer.manual_and_automatic_requests\r\nwhere\r\n\tservice_name = '[[service]]'\r\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\r\n\tand (('[[task]]' = 'main' and order_status is not null) or ('[[task]]' != 'main' and task_status is not null))\r\ngroup by\r\n\t1\r\norder by\r\n\t2 desc;"
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(*)\nfrom\n\tcustomer.manual_and_automatic_requests\nwhere\n\tservice_name = '[[service]]'\n\tand (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n\tand (('[[task]]' = 'main' and order_status is not null) or ('[[task]]' != 'main' and task_status is not null))"
    }
   ]
  },
  {
   "title": "Mean duration for successful tasks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\tservice_name,\r\n\tcase when '[[task]]'='main' then avg(extract(epoch from (order_stopped - order_started ))/ 60.0)\r\n\telse avg(extract(epoch from (task_stopped - task_started ))/ 60.0) end as duration\r\nfrom\r\n\tcustomer.manual_and_automatic_requests\r\nwhere\r\n  service_name='[[service]]'\r\n  and (('[[task]]' = 'main' and order_status = 'SUCCESS') or ('[[task]]' != 'main' and task_status = 'SUCCESS'))\r\n\tand (('[[task]]' = 'main' and order_status is not null) or ('[[task]]' != 'main' and task_status is not null))\r\n--\tand (so.order_stopped - so.order_started ) is not null\r\n--\tand so.order_started > '2020-05-13'\r\ngroup by\r\n\t1\r\norder by\r\n\t1;"
    }
   ]
  },
  {
   "title": "Customer Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "select\n  cellcode,\n  order_id,\n  case when '[[task]]'='main' then order_username else task_username end as username,\n  case when '[[task]]'='main' then order_received else task_started end as received,\n  case when '[[task]]'='main' then order_started else task_started end as started,\n  case when '[[task]]'='main' then order_stopped else task_stopped end as stopped,\n  case\n\t\twhen '[[task]]'='main' and order_status = 'FAILED' then -1\n\t\twhen '[[task]]'='main' and order_status = 'SUCCESS' then -2\n\t\twhen '[[task]]'='main' and order_status = 'RUNNING' then -3\n\t\twhen '[[task]]'='main' and order_status = 'RECEIVED' then -4\n\t\twhen '[[task]]'='main' and order_status = 'QUEUED' then -5\n\t\t\n\t\twhen '[[task]]'!='main' and task_status = 'FAILED' then -1\n\t\twhen '[[task]]'!='main' and task_status = 'SUCCESS' then -2\n\t\twhen '[[task]]'!='main' and task_status = 'RUNNING' then -3\n\t\twhen '[[task]]'!='main' and task_status = 'RECEIVED' then -4\n\t\twhen '[[task]]'!='main' and task_status = 'QUEUED' then -5\n\tend as status,\n\tcase when '[[task]]'='main' then order_json end as order_json\n  \nfrom\n  customer.manual_and_automatic_requests\nwhere\n  service_name='[[service]]'\n  and (('[[task]]' = 'main') or ('[[task]]' != 'main' and task_name = '[[task]]'))\n  and (('[[task]]' = 'main' and order_status is not null) or ('[[task]]' != 'main' and task_status is not null))\nORDER by\n  started desc"
    }
   ]
  }
 ]
}