log:
  level: "INFO"

entryPoints:
  web_http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web_secure_https
          scheme: https
          permanent: true
  web_secure_https:
    address: ":443"

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /configs

certificatesResolvers:
  myresolver:
    acme:
      email: IT-Services@geoville.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web_http