{
 "title": "CLCplus Backbone  Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processing Status",
   "type": "grafana-worldmap-panel",
   "description": "Internally finished Subproduction Units (Vector Class Attribution)",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n\tepu.spu_id as name,\n\tST_Y(ST_Transform(ST_Centroid(epu.wkb_geometry), 4326)) as latitude,\n\tST_X(ST_Transform(ST_Centroid(epu.wkb_geometry), 4326)) as longitude,\n\tMAX(case when tas.order_status = 'FAILED' then -1 when (tas.order_status = 'RUNNING' or tas.order_status = 'RECEIVED' or tas.order_status = 'QUEUED') then 0 when tas.order_status = 'SUCCESS' then 1 else -2 end) as value,\n\tMAX(case when tas.order_status = 'FAILED' then -1 when (tas.order_status = 'RUNNING' or tas.order_status = 'RECEIVED' or tas.order_status = 'QUEUED') then 0 when tas.order_status = 'SUCCESS' then 1 else -2 end) as metric\nfrom\n\tgrafana_monitoring.eu_production_units epu\nleft outer join (\n\tselect\n\t\t*\n\tfrom\n\t\tcustomer.tasks_and_services_spu\n\twhere\n\t\tservice_name = 'vector_class_attribution') as tas on\n\t\t(epu.spu_id = tas.subproduction_unit)\n\tgroup by\n\t\tST_Centroid(epu.wkb_geometry),\n\t\tname"
    }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<span style=\"padding-right: 300px;color:Whitehite\">Not started yet (-2)</span>\n<span style=\"padding-right: 300px;color:Red\">Failed (-1)</span>\n<span style=\"padding-right: 300px;color:Yellow\">Received, Queued, Running (0)</span>\n<span style=\"color:Green\">Success (1)</span>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processing Units Finished for Delivery",
   "type": "gauge",
   "description": "Number of finished processing units of the manual task \"T2 QC Postprocessing\"",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\tcount(*)\r\nfrom\r\n\tcustomer.manual_tasks mt\r\nwhere\r\n\tmt.status = 'SUCCESS'\r\n\tand mt.task_id = '2'"
    }
   ]
  },
  {
   "title": "Successful Processing Units",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "select\r\n  s.service_name,\r\n\tcount(DISTINCT so.order_json ->> 'processing_unit_name'::text)\r\nfrom\r\n\tcustomer.service_orders so,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand status = 'SUCCESS'\r\ngroup by s.service_name\r\norder by\r\n\t2 desc;"
    }
   ]
  },
  {
   "title": "Successful Sub-Production Units",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "select\r\n  s.service_name,\r\n\tcount(DISTINCT so.order_json ->> 'subproduction_unit_name'::text)\r\nfrom\r\n\tcustomer.service_orders so,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand status = 'SUCCESS'\r\ngroup by s.service_name\r\norder by\r\n\t2 desc;"
    }
   ]
  },
  {
   "title": "Mean duration for successful orders",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ts.service_name,\r\n\tavg(extract(epoch from (so.order_stopped - so.order_received ))/ 60.0) as duration\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand so.success is true\r\n\tand (so.order_stopped - so.order_started ) is not null\r\n\tand order_received > '2021-04-26 13:10'\r\n  group by\r\n\t1\r\norder by\r\n\t1;"
    }
   ]
  },
  {
   "title": "Failed Orders by Service",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ts.service_name,\r\n\tcount(*)\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand so.order_received >'2021-04-26 13:10'\r\n\tand so.status != 'SUCCESS'\r\ngroup by\r\n\t1\r\norder by\r\n\t2 desc;"
    }
   ]
  }
 ]
}